// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jpqhwcjisjnqytygrmrr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpwcWh3Y2ppc2pucXl0eWdybXJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNDUyMzIsImV4cCI6MjA2NTYyMTIzMn0.r0rRfb8YNneAbCfiXR4ACsYxpQMVFMXXamrasMlDazQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);