// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://swbrpbdtxwxqbvvbpaba.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3YnJwYmR0eHd4cWJ2dmJwYWJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwMTIwNDMsImV4cCI6MjA1NjU4ODA0M30.oraqRwrTMICVgOlqzeHjmTTZgiVwnuS0g1YvI9o-RPA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);